local/script/grot: Format

diff --git a/.local/script/grot b/.local/script/grot
--- a/.local/script/grot
+++ b/.local/script/grot
@@ -3,7 +3,7 @@
 # grot: grim (+slurp) screenshot
 
 usage() (
-    printf "Usage: grot \e[3mscope\e[0m
+	printf "Usage: grot \e[3mscope\e[0m
 
 \e[3mscope\e[0m:
   - r|region
@@ -13,68 +13,68 @@ usage() (
 )
 
 notify() (
-    SCOPE="$1"
-    PATH="$2"
-    FILENAME="$3"
+	SCOPE="$1"
+	PATH="$2"
+	FILENAME="$3"
 
-    # FIX: notify-send not found in here or if with `if` block
-    [ -f "{$PATH}/$FILENAME" ] &&
-        notify-send "$SCOPE Screenshot" "$FILENAME" \
-            -t 2500 \
-            -i "$PATH/$FILENAME"
+	# FIX: notify-send not found in here or if with `if` block
+	[ -f "{$PATH}/$FILENAME" ] &&
+		notify-send "$SCOPE Screenshot" "$FILENAME" \
+			-t 2500 \
+			-i "$PATH/$FILENAME"
 )
 
 shot() (
-    grim -t jpeg -q 100 "$@"
+	grim -t jpeg -q 100 "$@"
 )
 
 region() (
-    shot -g "$(slurp)" "$@"
+	shot -g "$(slurp)" "$@"
 )
 
 full() (
-    shot "$@"
+	shot "$@"
 )
 
 pick() (
-    grim -g "$(slurp -p)" -t ppm - | convert - -format '%[pixel:p{0,0}]' txt:-
+	grim -g "$(slurp -p)" -t ppm - | convert - -format '%[pixel:p{0,0}]' txt:-
 )
 
 main() (
-    SCOPE="$1"
-    FN="$1"
-    FILENAME="$(date +'%Y%m%d_%H%M%S').jpeg"
-    SAVEPATH="${GRIM_DEFAULT_DIR:-$XDG_PICTURES_DIR:-$HOME/picture}"
+	SCOPE="$1"
+	FN="$1"
+	FILENAME="$(date +'%Y%m%d_%H%M%S').jpeg"
+	SAVEPATH="${GRIM_DEFAULT_DIR:-$XDG_PICTURES_DIR:-$HOME/picture}"
 
-    case $SCOPE in
-        "r" | "region")
-            SCOPE="Region"
-            FN="region"
-            ;;
-        "f" | "full")
-            SCOPE="Fullscreen"
-            FN="full"
-            ;;
-        "p" | "pick")
-            pick
-            exit
-            ;;
-        "h" | "help")
-            usage
-            exit
-            ;;
-        *)
-            printf "\e[0;91m%s\e[0m " "$SCOPE"
-            printf "is an invalid argument.\n"
-            usage
-            exit 1
-            ;;
-    esac
+	case $SCOPE in
+		"r" | "region")
+			SCOPE="Region"
+			FN="region"
+			;;
+		"f" | "full")
+			SCOPE="Fullscreen"
+			FN="full"
+			;;
+		"p" | "pick")
+			pick
+			exit
+			;;
+		"h" | "help")
+			usage
+			exit
+			;;
+		*)
+			printf "\e[0;91m%s\e[0m " "$SCOPE"
+			printf "is an invalid argument.\n"
+			usage
+			exit 1
+			;;
+	esac
 
-    "$FN" "$SAVEPATH/$FILENAME"
-    notify-send "$SCOPE Screenshot" "$FILENAME" \
-        -t 2500 \
-        -i "$SAVEPATH/$FILENAME"
+	"$FN" "$SAVEPATH/$FILENAME"
+	notify-send "$SCOPE Screenshot" "$FILENAME" \
+		-t 2500 \
+		-i "$SAVEPATH/$FILENAME"
 )
 
 main "$@"
